"""Unit tests for dashboard analytics helpers (no DB / no PostGIS)."""
from __future__ import annotations

from datetime import date
from pathlib import Path

import pytest

from app.services.dashboard_analytics import (
    OBLAST_NAME_UK,
    compute_risk_score,
    find_oblast_for_centroid,
    oblast_avg_ndvi,
    oblast_avg_yield,
    oblast_baseline_year,
    oblast_name_uk,
    phenology_calendar,
    phenology_phase,
    reset_oblast_baseline_cache,
    reset_oblast_polygons_cache,
    reset_oblast_yield_baseline_cache,
)


# ─── Phenology ──────────────────────────────────────────────


def test_phenology_unknown_crop_returns_none():
    assert phenology_phase("bananas") is None


def test_phenology_wheat_summer_is_harvest():
    assert phenology_phase("wheat", date(2026, 8, 15)) == "harvest"


def test_phenology_wheat_winter_is_dormancy():
    """Wheat dormancy spans November–March — wraparound month range."""
    assert phenology_phase("wheat", date(2026, 1, 15)) == "dormancy"
    assert phenology_phase("wheat", date(2026, 12, 5)) == "dormancy"


def test_phenology_corn_july_is_flowering():
    assert phenology_phase("corn", date(2026, 7, 10)) == "flowering"


def test_phenology_calendar_lists_all_phases():
    cal = phenology_calendar("sunflower")
    phases = [p["phase"] for p in cal]
    assert "sowing" in phases
    assert "harvest" in phases
    assert all(1 <= p["start_month"] <= 12 for p in cal)
    assert all(1 <= p["end_month"] <= 12 for p in cal)


# ─── Risk score ─────────────────────────────────────────────


def test_risk_score_zero_when_clean():
    score, factors = compute_risk_score(
        current_ndvi=0.65,
        oblast_avg_ndvi=0.62,
        alerts_by_severity={},
    )
    assert score == 0
    assert factors == []


def test_risk_score_ndvi_deficit_penalises():
    score, factors = compute_risk_score(
        current_ndvi=0.30,
        oblast_avg_ndvi=0.65,
        alerts_by_severity={},
    )
    assert score > 0
    assert any("NDVI" in f for f in factors)


def test_risk_score_critical_alert_heavy_weight():
    score, factors = compute_risk_score(
        current_ndvi=0.60,
        oblast_avg_ndvi=0.60,
        alerts_by_severity={"critical": 1},
    )
    # One critical alone should land roughly 30 points.
    assert 25 <= score <= 50
    assert any("Alert" in f or "критичних" in f for f in factors)


def test_risk_score_caps_at_100():
    score, _ = compute_risk_score(
        current_ndvi=0.10,
        oblast_avg_ndvi=0.80,
        alerts_by_severity={"warning": 5, "critical": 5},
        recent_soil_moisture=0.08,  # below 0.18 threshold → drought flag
        heat_days_recent=10,
    )
    assert score == 100


def test_risk_score_low_ndvi_standalone_still_flags():
    """Even without an oblast baseline, a very low NDVI alone is a flag."""
    score, factors = compute_risk_score(
        current_ndvi=0.20,
        oblast_avg_ndvi=None,
        alerts_by_severity={},
    )
    assert score > 0
    assert any("NDVI" in f for f in factors)


def test_risk_score_low_soil_moisture_flags_drought():
    """Volumetric soil moisture below the 18 % threshold raises a
    drought-style risk factor — replaces the older `drought_days < 1mm`
    counter which mis-fired after recent rain. Exactly matches the
    user-facing label `Низька волога ґрунту (NN%)`."""
    score, factors = compute_risk_score(
        current_ndvi=0.55,
        oblast_avg_ndvi=0.55,
        alerts_by_severity={},
        recent_soil_moisture=0.12,
    )
    assert score >= 15
    assert any("волога ґрунту" in f.lower() for f in factors)
    assert any("12%" in f for f in factors)


def test_risk_score_high_soil_moisture_does_not_flag():
    """Soil moisture above 18 % means the soil is well-watered — no
    drought flag, even though zero precip would have triggered the
    old day-counter version of the rule."""
    score, factors = compute_risk_score(
        current_ndvi=0.55,
        oblast_avg_ndvi=0.55,
        alerts_by_severity={},
        recent_soil_moisture=0.22,
    )
    assert not any("волога ґрунту" in f.lower() for f in factors)
    # No other factors triggered either — clean field.
    assert score == 0


def test_risk_score_missing_soil_moisture_does_not_flag():
    """When the weather sync hasn't populated moisture (fresh field /
    Open-Meteo gap), the absence of data must not be treated as
    drought — `None` is a missing signal, not a zero reading."""
    score, factors = compute_risk_score(
        current_ndvi=0.55,
        oblast_avg_ndvi=0.55,
        alerts_by_severity={},
        recent_soil_moisture=None,
    )
    assert not any("волога ґрунту" in f.lower() for f in factors)
    assert score == 0


# ─── Oblast resolver (point-in-polygon) ─────────────────────


# Geojson lives under backend/data/raw/ — these tests assume it's been
# generated by `scripts/download_oblast_geometries.py`. If the project is
# cloned without that asset, the lookup tests degrade to "skip".
_GEOJSON_PATH = Path("data/raw/ukraine_oblasts.geojson")


@pytest.fixture(autouse=True)
def _reset_oblast_caches():
    """Drop both LRU caches before each test so polygon/parquet state can't
    leak across tests (especially important if a future test rewrites the
    fixture data)."""
    reset_oblast_polygons_cache()
    reset_oblast_baseline_cache()
    yield
    reset_oblast_polygons_cache()
    reset_oblast_baseline_cache()


@pytest.mark.skipif(not _GEOJSON_PATH.exists(), reason="oblast geojson missing")
def test_find_oblast_kyiv_centroid_returns_kiev_city():
    # Khreshchatyk / Maidan area — should fall inside the Kyiv City polygon
    # (city is carved out of Kyiv oblast in Natural Earth's split).
    assert find_oblast_for_centroid(50.4501, 30.5234) == "Kiev City"


@pytest.mark.skipif(not _GEOJSON_PATH.exists(), reason="oblast geojson missing")
def test_find_oblast_kharkiv_centroid():
    assert find_oblast_for_centroid(49.9935, 36.2304) == "Kharkiv"


@pytest.mark.skipif(not _GEOJSON_PATH.exists(), reason="oblast geojson missing")
def test_find_oblast_chernihiv_centroid():
    assert find_oblast_for_centroid(51.4982, 31.2893) == "Chernihiv"


@pytest.mark.skipif(not _GEOJSON_PATH.exists(), reason="oblast geojson missing")
def test_find_oblast_lviv_centroid_uses_natural_earth_name():
    # Natural Earth spells Lviv with an apostrophe (`L'viv`). The function
    # must return that exact key so the translation map can resolve it.
    assert find_oblast_for_centroid(49.8397, 24.0297) == "L'viv"


@pytest.mark.skipif(not _GEOJSON_PATH.exists(), reason="oblast geojson missing")
def test_find_oblast_outside_ukraine_returns_none():
    # Berlin — outside every Ukrainian polygon.
    assert find_oblast_for_centroid(52.5200, 13.4050) is None


def test_find_oblast_none_coords_returns_none():
    assert find_oblast_for_centroid(None, None) is None
    assert find_oblast_for_centroid(50.0, None) is None
    assert find_oblast_for_centroid(None, 30.0) is None


# ─── Oblast NDVI baseline ───────────────────────────────────


_PARQUET_PATH = Path("data/processed/training_set_v2.parquet")


@pytest.mark.skipif(not _PARQUET_PATH.exists(), reason="training_set_v2.parquet missing")
def test_oblast_avg_ndvi_returns_known_value_for_chernihiv():
    """Chernihiv is in the Week 6 dataset; the lookup should return the
    aggregated peak NDVI (≈0.76–0.85 range across 2019–2023)."""
    val = oblast_avg_ndvi("Chernihiv", 2023)
    assert val is not None
    assert 0.5 < val < 1.0  # NDVI peak sanity bounds


@pytest.mark.skipif(not _PARQUET_PATH.exists(), reason="training_set_v2.parquet missing")
def test_oblast_avg_ndvi_falls_back_to_latest_year():
    """Requesting a year that isn't in the parquet should not return None —
    it should fall back to the most-recent year for that oblast."""
    val = oblast_avg_ndvi("Chernihiv", 2099)
    assert val is not None  # 2099 absent → fallback fires


@pytest.mark.skipif(not _PARQUET_PATH.exists(), reason="training_set_v2.parquet missing")
def test_oblast_baseline_year_returns_most_recent_year():
    """The companion helper should report which year the baseline came
    from. For the canonical 2019–2023 dataset that's 2023."""
    yr = oblast_baseline_year("Chernihiv")
    assert yr in {2019, 2020, 2021, 2022, 2023}


def test_oblast_avg_ndvi_unknown_oblast_returns_none():
    """Atlantis isn't in the parquet — must degrade gracefully so the UI
    can show "oblast not yet covered" without throwing."""
    assert oblast_avg_ndvi("Atlantis", 2023) is None
    assert oblast_baseline_year("Atlantis") is None


def test_oblast_avg_ndvi_none_input_returns_none():
    assert oblast_avg_ndvi(None, 2023) is None
    assert oblast_baseline_year(None) is None


# ─── Per-(oblast, crop) Держстат yield baseline ────────────


_V3_PARQUET_PATH = Path("data/processed/training_set_v3.parquet")


@pytest.fixture(autouse=True)
def _reset_yield_cache():
    """Each yield-baseline test starts with a clean lru_cache so a
    previous test's parquet read can't leak through."""
    reset_oblast_yield_baseline_cache()
    yield
    reset_oblast_yield_baseline_cache()


@pytest.mark.skipif(
    not _V3_PARQUET_PATH.exists(),
    reason="training_set_v3.parquet missing",
)
def test_oblast_avg_yield_returns_wheat_baseline_for_vinnytsia():
    """Vinnytsia is fully covered by the Держstat 2018–2021 dataset.
    Wheat yields there typically range 3.5–5.5 t/ha — sanity-bound the
    lookup to that band."""
    val, year = oblast_avg_yield("Vinnytsia", "wheat", 2021)
    assert val is not None
    assert year is not None
    assert 2.0 < val < 7.0
    assert year in {2018, 2019, 2020, 2021}


@pytest.mark.skipif(
    not _V3_PARQUET_PATH.exists(),
    reason="training_set_v3.parquet missing",
)
def test_oblast_avg_yield_accepts_natural_earth_spelling():
    """Crucial regression: `find_oblast_for_centroid` returns Natural
    Earth spellings ("L'viv"), while the v3 parquet stores "Lviv".
    `iso_from_any_name` normalises both sides; the lookup must work
    regardless of which spelling the caller passes in."""
    a, _ = oblast_avg_yield("L'viv", "wheat", 2021)
    b, _ = oblast_avg_yield("Lviv", "wheat", 2021)
    # Both inputs map to the same ISO code → identical lookup result.
    assert a == b
    assert a is not None


@pytest.mark.skipif(
    not _V3_PARQUET_PATH.exists(),
    reason="training_set_v3.parquet missing",
)
def test_oblast_avg_yield_falls_back_to_latest_year():
    """Requesting a year that isn't in the dataset (2099) must
    silently fall back to the most-recent year available for that
    (oblast, crop), so the UI always gets a usable baseline when
    one exists in any year."""
    val, year = oblast_avg_yield("Vinnytsia", "wheat", 2099)
    assert val is not None
    assert year is not None
    assert year < 2099


def test_oblast_avg_yield_unknown_oblast_returns_none():
    """Atlantis isn't in the dataset — must degrade gracefully."""
    val, year = oblast_avg_yield("Atlantis", "wheat", 2021)
    assert val is None
    assert year is None


def test_oblast_avg_yield_none_inputs_return_none():
    """Both oblast and crop are required; either being None short-
    circuits to (None, None) without raising or hitting the parquet."""
    assert oblast_avg_yield(None, "wheat", 2021) == (None, None)
    assert oblast_avg_yield("Vinnytsia", None, 2021) == (None, None)
    assert oblast_avg_yield(None, None, None) == (None, None)


# ─── Ukrainian display names ────────────────────────────────


def test_oblast_name_uk_translates_canonical_names():
    assert oblast_name_uk("Kharkiv") == "Харківська обл."
    assert oblast_name_uk("L'viv") == "Львівська обл."
    assert oblast_name_uk("Kiev City") == "м. Київ"


def test_oblast_name_uk_falls_back_to_english_for_unknown():
    """Unknown name passes through unchanged so the UI never shows a blank
    cell — better to display the raw Natural Earth label than a hole."""
    assert oblast_name_uk("Atlantis") == "Atlantis"


def test_oblast_name_uk_none_returns_none():
    assert oblast_name_uk(None) is None
    assert oblast_name_uk("") is None


def test_oblast_name_uk_covers_all_25_natural_earth_oblasts():
    """Sanity: the translation map must include every oblast that Natural
    Earth's Ukrainian admin-1 split publishes (25 = 24 oblasts + Kyiv City).
    A missed entry shows up as an English string in the UI."""
    assert len(OBLAST_NAME_UK) == 25
